// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyivgcvvlmuooqhwzwlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5aXZnY3Z2bG11b29xaHd6d2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3MjI5NTEsImV4cCI6MjA1MTI5ODk1MX0.zha6h1dii23IGNUxH7ZyYwAKqkYo9dZ0_QHwaSn7BRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);